### ISSUE TITLE
helm-ag--edit: Text is read-only!

### ISSUE THREAD

**Issue by iocanel** [emacsorphanage/emacs-helm-ag#331]
- Emacs version: 26.2
- Operating system: linux 
- Search command: ag
- Last value of `helm-ag--last-command`

`("ag" "--nocolor" "--nogroup" "--ignore" "TAGS" "--ignore" ".#*" "--ignore" "*.o" "--ignore" "*~" "--ignore" "*.bin" "--ignore" "*.lbin" "--ignore" "*.so" "--ignore" "*.a" "--ignore" "*.ln" "--ignore" "*.blg" "--ignore" "*.bbl" "--ignore" "*.elc" "--ignore" "*.lof" "--ignore" "*.glo" "--ignore" "*.idx" "--ignore" "*.lot" "--ignore" "*.fmt" "--ignore" "*.tfm" "--ignore" "*.class" "--ignore" "*.fas" "--ignore" "*.lib" "--ignore" "*.mem" "--ignore" "*.x86f" "--ignore" "*.sparcf" "--ignore" "*.dfsl" "--ignore" "*.pfsl" "--ignore" "*.d64fsl" "--ignore" "*.p64fsl" "--ignore" "*.lx64fsl" "--ignore" "*.lx32fsl" "--ignore" "*.dx64fsl" "--ignore" "*.dx32fsl" "--ignore" "*.fx64fsl" "--ignore" "*.fx32fsl" "--ignore" "*.sx64fsl" "--ignore" "*.sx32fsl" "--ignore" "*.wx64fsl" "--ignore" "*.wx32fsl" "--ignore" "*.fasl" "--ignore" "*.ufsl" "--ignore" "*.fsl" "--ignore" "*.dxl" "--ignore" "*.lo" "--ignore" "*.la" "--ignore" "*.gmo" "--ignore" "*.mo" "--ignore" "*.toc" "--ignore" "*.aux" "--ignore" "*.cp" "--ignore" "*.fn" "--ignore" "*.ky" "--ignore" "*.pg" "--ignore" "*.tp" "--ignore" "*.vr" "--ignore" "*.cps" "--ignore" "*.fns" "--ignore" "*.kys" "--ignore" "*.pgs" "--ignore" "*.tps" "--ignore" "*.vrs" "--ignore" "*.pyc" "--ignore" "*.pyo" "--ignore" "{arch}" "--ignore" "_darcs" "--ignore" "_MTN" "--ignore" ".bzr" "--ignore" ".hg" "--ignore" ".git" "--ignore" ".svn" "--ignore" ".src" "--ignore" "MCVS" "--ignore" "CVS" "--ignore" "RCS" "--ignore" "SCCS" "--ignore" ".idea/" "--ignore" ".ensime_cache/" "--ignore" ".eunit/" "--ignore" ".git/" "--ignore" ".hg/" "--ignore" ".fslckout/" "--ignore" "_FOSSIL_/" "--ignore" ".bzr/" "--ignore" "_darcs/" "--ignore" ".tox/" "--ignore" ".svn/" "--ignore" ".stack-work/" "idee-project")`

### Actual behavior
I am using `helm-projectile-ag` to search my project. The search part is working as expected. While I am still in search mode I press `C-c C-e` to go to edit mode. It doesn't work and I am getting this error:

`Error during redisplay: (eval (propertize (format "[AG process finished - (%s results)] " (helm-get-candidate-number)) (quote face) (quote helm-grep-finish))) signaled (error "No buffer named *helm*")
helm-ag--edit: Text is read-only`

### Expected behavior
I would expect to be able to edit and then save.

### Steps to reproduce

1. helm-projectile-ag
2. search for a pattern
3. press `C-c C-e`

### Other notes
This used to work for me fine and suddendly broke without me updating anything related to helm, ag or projectile.

**Comment by iocanel** [comment]
Playing a little bit more with it, it seems that sometimes it works  (but most it doesn't).
Haven't discerned a pattern yet.

**Comment by cedarbaum** [comment]
I get a similar error when `*helm-ag-edit*` buffer has not been deleted after a previous search/edit. When `helm-ag-edit` is called, it tries to call `erase-buffer` on the `*helm-ag-edit*` buffer. However, this buffer can contain readonly characters (the file name / line number prefixes) from a previous search and, if it does, the command will fail.

This can be solved by navigating to the buffer (`C-x b *helm-ag-edit* RET`) and either committing (`C-c C-c`) or discarding (`C-c C-k`) the previous edits. Either command will also delete the buffer, so the next call to `helm-ag-edit` will create a new buffer without any readonly characters.

**Comment by twlz0ne** [comment]
Same here

**Comment by fleutot** [comment]
I have a [PR](https://github.com/syohex/emacs-helm-ag/pull/340) about this. I know next to nothing about possible side effects, but I'd be happy to know.

**Comment by syohex** [comment]
Sorry late reply. I have merged your PR. Please check latest version.
